spring.application.name=backend
server.port=8080

aws.region=us-east-1
aws.s3.bucket-name=YOUR_BUCKET_NAME

aws.dynamodb.table.login=login
aws.dynamodb.table.music=music
aws.dynamodb.table.subscriptions=subscriptions