spring.application.name=backend
server.port=8080

aws.region=us-east-1
aws.s3.bucket-name=music-app-images-211-rmit

aws.dynamodb.table.login=login
aws.dynamodb.table.music=music
aws.dynamodb.table.subscriptions=subscriptions